/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package marius.empleado.view;

import javax.swing.JOptionPane;
import marius.empleado.Entity.Empleado;
import marius.empleado.negocio.EmpleadoNegocio;

/**
 *
 * @author mariu
 */
public class FrmEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form FrmEmpleado
     */
    private EmpleadoNegocio enegocio= new EmpleadoNegocio();

    public FrmEmpleado() {
        initComponents();
        listarEmpleado();
        idMax();

    }

    //metodo
    public void listarEmpleado(){
        
        enegocio.listarEmpleado(tbEmpleado);
 //   initComponents();
    }
    public void idMax(){
    
   txtIdEmpleado.setText( enegocio.getMaxID()+"");
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupEstado = new javax.swing.ButtonGroup();
        groupGenero = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        rdCasado = new javax.swing.JRadioButton();
        rdSoltero = new javax.swing.JRadioButton();
        rdMasculino = new javax.swing.JRadioButton();
        rdFeminino = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleado = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnAgragar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(229, 245, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        txtIdEmpleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIdEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 220, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("FORMULARIO EMPLEADO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 20));

        txtNombres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 220, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("NOMBRES:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("APELLDOS:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        txtApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 220, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("DNI:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 20));

        txtDni.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 220, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("ESTADO CIVIL:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 140, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("GENERO:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("EDAD:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 120, 20));

        txtEdad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 220, 30));

        groupEstado.add(rdCasado);
        rdCasado.setText("Casado");
        rdCasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCasadoActionPerformed(evt);
            }
        });
        jPanel1.add(rdCasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        groupEstado.add(rdSoltero);
        rdSoltero.setText("Soltero");
        rdSoltero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSolteroActionPerformed(evt);
            }
        });
        jPanel1.add(rdSoltero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        groupGenero.add(rdMasculino);
        rdMasculino.setText("Masculino");
        rdMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMasculinoActionPerformed(evt);
            }
        });
        jPanel1.add(rdMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        groupGenero.add(rdFeminino);
        rdFeminino.setText("Feminino");
        rdFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFemininoActionPerformed(evt);
            }
        });
        jPanel1.add(rdFeminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        tbEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEmpleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 101, 470, 410));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, -1, -1));

        btnAgragar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgragar.setText("Agregar");
        btnAgragar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgragarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgragar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, -1, -1));

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmpleadoActionPerformed

    private void rdCasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdCasadoActionPerformed

    private void rdSolteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSolteroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdSolteroActionPerformed

    private void rdMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdMasculinoActionPerformed

    private void rdFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFemininoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
    System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    limpiar();
    
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgragarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgragarActionPerformed
        if (txtIdEmpleado.getText().isEmpty()||txtNombres.getText().isEmpty()||txtApellidos.getText().isEmpty()||txtDni.getText().isEmpty()
                || txtEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llena todos los campos!");
        }else{
            char estado;
            char genero;
            if (rdCasado.isSelected()) {
                estado='C';
            }else{
            estado='S';
            
            }
             if (rdFeminino.isSelected()) {
                genero='F';
            }else{
            genero='M';
            
            }
            
            Empleado emp= new Empleado();
            emp.setIdEmpleado(Integer.parseInt(txtIdEmpleado.getText()));
            emp.setNombres(txtNombres.getText());
            emp.setApellidos(txtApellidos.getText());
            emp.setDni(txtDni.getText());
            emp.setEstadoCivil(estado);
            emp.setGenero(genero);
         emp.setEdad(Integer.parseInt(txtEdad.getText()));
        String mensaje= enegocio.agragarEmpleado(emp);
        limpiar();
        listarEmpleado();//mostrar lista empleados
        }
    }//GEN-LAST:event_btnAgragarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (txtIdEmpleado.getText().isEmpty()||txtNombres.getText().isEmpty()||txtApellidos.getText().isEmpty()||txtDni.getText().isEmpty()
                || txtEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llena todos los campos!");
        }else{
            char estado;
            char genero;
            if (rdCasado.isSelected()) {
                estado='C';
            }else{
            estado='S';
            
            }
             if (rdFeminino.isSelected()) {
                genero='F';
            }else{
            genero='M';
            }
            Empleado emp= new Empleado();
            emp.setIdEmpleado(Integer.parseInt(txtIdEmpleado.getText()));
            emp.setNombres(txtNombres.getText());
            emp.setApellidos(txtApellidos.getText());
            emp.setDni(txtDni.getText());
            emp.setEstadoCivil(estado);
            emp.setGenero(genero);
         emp.setEdad(Integer.parseInt(txtEdad.getText()));
        String mensaje= enegocio.modificarEmpleado(emp);
        limpiar();
        listarEmpleado();//mostrar lista empleados
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
   
        String mensaje= enegocio.eliminarEmpleado(Integer.parseInt(txtIdEmpleado.getText()));
        limpiar();
        listarEmpleado();//mostrar lista empleados
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tbEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEmpleadoMouseClicked
      int seleccion = tbEmpleado.rowAtPoint(evt.getPoint());
         txtIdEmpleado.setText(tbEmpleado.getValueAt(seleccion, 0)+"");
         txtNombres.setText(tbEmpleado.getValueAt(seleccion, 1)+"");
         txtApellidos.setText(tbEmpleado.getValueAt(seleccion, 2)+"");
         txtDni.setText(tbEmpleado.getValueAt(seleccion, 3)+"");
         txtEdad.setText(tbEmpleado.getValueAt(seleccion, 5)+"");
  
        
        String estado=tbEmpleado.getValueAt(seleccion, 6)+"";
        if (estado.equals("S")) {
            rdSoltero.setSelected(true);
        }else{
        rdCasado.setSelected(true);
        
        }
        String genero= tbEmpleado.getValueAt(seleccion, 4)+"";
        
         if (genero.equals("F")) {
            rdFeminino.setSelected(true);
        }else{
        rdMasculino.setSelected(true);
        
        }
        
    
    }//GEN-LAST:event_tbEmpleadoMouseClicked
    public void limpiar(){
         txtIdEmpleado.setText("");
      txtEdad.setText("");
       txtNombres.setText("");
        txtApellidos.setText("");
        txtDni.setText("");
        groupEstado.clearSelection();
        groupGenero.clearSelection();
        idMax();//dame el id +1
    }
   
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgragar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup groupEstado;
    private javax.swing.ButtonGroup groupGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdCasado;
    private javax.swing.JRadioButton rdFeminino;
    private javax.swing.JRadioButton rdMasculino;
    private javax.swing.JRadioButton rdSoltero;
    private javax.swing.JTable tbEmpleado;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
